### ISSUE TITLE
WAYF menu changes

### ISSUE THREAD

**Issue by dongourley** [WRLC/aladin-redirects#3]
Please change the label for us from 'WRLC SCF' to just 'WRLC'.

Please add 'Georgetown Law' and 'Trinity Washington University' to the menu and these entries to the <tt>proxies</tt> array:
<pre>
    'GTL': 'https://proxygt-law.wrlc.org/login?url={}',
    'TR': 'https://proxytr.wrlc.org/login?url={}',
</pre>

**Comment by tomboone** [comment]
Done. Merged in Pull Request #4. Deploying now.

**Comment by tomboone** [comment]
Deployed.
